/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:1c1da86c-d1a3-4cf7-9a02-118b25d1319f",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_NzYo2EUp0",
    "aws_user_pools_web_client_id": "321f3mq43jqkcl259j09ku910e",
    "oauth": {}
};


export default awsmobile;
