/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:2060af26-36fc-4058-abac-6ff3ecba0f2e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_RG4BhOJL6",
    "aws_user_pools_web_client_id": "i7ss914kudcu43ekeqtotn2t",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://xoball3a45fpbkyi4gc4aeppze.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-s7cdvqpfvbfzregwbhz37ylagy"
};


export default awsmobile;
